# Generated by Django 5.1.3 on 2024-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Открыт"),
                    ("in_progress", "В работе"),
                    ("completed", "Завершен"),
                ],
                default="open",
                max_length=50,
            ),
        ),
    ]
