# Generated by Django 5.1.3 on 2024-11-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="is_accepted",
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("accepted", "Принята"),
                    ("rejected", "Отклонена"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
