# Generated by Django 5.1.3 on 2024-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_report_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("accepted", "Принята"),
                    ("rejected", "Отклонена"),
                    ("submitted", "Отчет отправлен"),
                    ("completed", "Завершена"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
