# Generated by Django 5.1.3 on 2024-11-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("accepted", "Принята"),
                    ("rejected", "Отклонена"),
                    ("submitted", "Отчет отправлен"),
                    ("report_rejected", "Отчет отклонен"),
                    ("report_accepted", "Отчет принят"),
                    ("completed", "Завершена"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Открыт"),
                    ("in_progress", "В работе"),
                    ("completed", "Завершен"),
                    ("closed", "Закрыт"),
                ],
                default="open",
                max_length=50,
            ),
        ),
    ]
