# Generated by Django 5.1.3 on 2024-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_application_status_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="deadline_notification_sent",
            field=models.DateField(blank=True, null=True),
        ),
    ]
