# Generated by Django 5.1.3 on 2024-11-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_application_deadline_notification_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_text",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
