# Generated by Django 5.1.3 on 2024-11-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_report_report_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_file",
            field=models.FileField(
                blank=True, null=True, upload_to="reports/", verbose_name="Файл отчета"
            ),
        ),
    ]
