# Generated by Django 5.1.3 on 2024-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_report_report_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_text",
            field=models.TextField(verbose_name="Текстовый отчет"),
        ),
    ]
