# Generated by Django 5.1.3 on 2024-11-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_report_report_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("accepted", "Принята"),
                    ("rejected", "Отклонена"),
                    ("rejected_final", "Отклонена (выбран другой исполнитель)"),
                    ("submitted", "Отчет отправлен"),
                    ("report_rejected", "Отчет отклонен"),
                    ("report_accepted", "Отчет принят"),
                    ("completed", "Завершена"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
