# Generated by Django 5.1.3 on 2024-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="reports/%Y/%m/%d/",
                verbose_name="Файл отчета",
            ),
        ),
    ]
